import Navigation from "../components/navigation"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* 이렇게 하면 각 페이지에 컴포넌트를 일일히 넣지 않아도 됨! */}
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
